package com.rms.services.schema;

import javax.xml.ws.WebFault;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebFault(name = "fault", targetNamespace = "http://www.remitservices.com/ScreeningService/")
public class RMSException extends Exception {

	/**
	 * Java type that goes as soapenv:Fault detail element.
	 * 
	 */
	private BaseFault faultInfo;

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 */
	public RMSException(String message, BaseFault faultInfo) {
		super(message);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @param message
	 * @param faultInfo
	 * @param cause
	 */
	public RMSException(String message, BaseFault faultInfo, Throwable cause) {
		super(message, cause);
		this.faultInfo = faultInfo;
	}

	/**
	 * 
	 * @return returns fault bean: com.rms.services.schema.BaseFault
	 */
	public BaseFault getFaultInfo() {
		return faultInfo;
	}

}
