package com.rms.services.schema;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ScreeningService", targetNamespace = "http://www.remitservices.com/ScreeningService/")
public interface ScreeningService {

	/**
	 * 
	 * @param context
	 * @param entityId
	 * @return returns com.rms.services.schema.SearchResults
	 * @throws RMSException
	 */
	@WebMethod
	@WebResult(name = "searchResults", targetNamespace = "")
	@RequestWrapper(localName = "getEntityDetail", targetNamespace = "http://www.remitservices.com/ScreeningService/", className = "com.rms.services.schema.GetEntityDetail")
	@ResponseWrapper(localName = "getEntityDetailResponse", targetNamespace = "http://www.remitservices.com/ScreeningService/", className = "com.rms.services.schema.GetEntityDetailResponse")
	public SearchResults getEntityDetail(
			@WebParam(name = "entityId", targetNamespace = "") Integer entityId,
			@WebParam(name = "context", targetNamespace = "") Context context)
			throws RMSException;

	/**
	 * 
	 * @param searchCriteria
	 * @param context
	 * @return returns java.util.List<com.rms.services.schema.SearchResults>
	 * @throws RMSException
	 */
	@WebMethod
	@WebResult(name = "searchResults", targetNamespace = "")
	@RequestWrapper(localName = "searchEntities", targetNamespace = "http://www.remitservices.com/ScreeningService/", className = "com.rms.services.schema.SearchEntities")
	@ResponseWrapper(localName = "searchEntitiesResponse", targetNamespace = "http://www.remitservices.com/ScreeningService/", className = "com.rms.services.schema.SearchEntitiesResponse")
	public List<SearchResults> searchEntities(
			@WebParam(name = "context", targetNamespace = "") Context context,
			@WebParam(name = "searchCriteria", targetNamespace = "") SearchCriteria searchCriteria)
			throws RMSException;

}
